#!/usr/bin/env python3
"""Build the single, self-extracting install.sh from the reviewable source tree."""
import argparse
import base64
import hashlib
import io
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def build():
    files = sorted([*ROOT.joinpath("src").rglob("*.py"), *ROOT.joinpath("web").glob("*"),
                    ROOT / "dependencies.lock.json", ROOT / "LICENSE", ROOT / "THIRD_PARTY.md"])
    memory = io.BytesIO()
    with zipfile.ZipFile(memory, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in files:
            info = zipfile.ZipInfo(path.relative_to(ROOT).as_posix(), date_time=(2026, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            archive.writestr(info, path.read_bytes())
    payload = memory.getvalue()
    encoded = base64.b64encode(payload).decode()
    lines = "\n".join(encoded[i:i+100] for i in range(0, len(encoded), 100))
    shell = '''#!/usr/bin/env bash
# Generated by tools/build_installer.py. Source: https://github.com/ievq00/vless-telegram-installer
set -Eeuo pipefail
umask 077
if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
    echo "Запустите эту команду через sudo." >&2
    exit 1
fi
if ! command -v python3 >/dev/null 2>&1; then
    export DEBIAN_FRONTEND=noninteractive
    apt-get -o DPkg::Lock::Timeout=120 update
    apt-get -o DPkg::Lock::Timeout=120 install -y --no-install-recommends python3 ca-certificates
fi
vt_tmp=$(mktemp -d /tmp/vt-installer.XXXXXXXX)
trap '[[ "$vt_tmp" == /tmp/vt-installer.* ]] && rm -rf -- "$vt_tmp"' EXIT
python3 - "$vt_tmp" <<'VT_BUNDLE_PYTHON'
import base64,hashlib,io,sys,zipfile
from pathlib import Path
payload=base64.b64decode("""__PAYLOAD__""")
if hashlib.sha256(payload).hexdigest() != "__HASH__":
    raise SystemExit("Установщик повреждён: контрольная сумма не совпадает.")
root=Path(sys.argv[1]).resolve()
with zipfile.ZipFile(io.BytesIO(payload)) as archive:
    for item in archive.infolist():
        target=(root/item.filename).resolve()
        if not target.is_relative_to(root):
            raise SystemExit("Некорректный путь внутри установщика.")
    archive.extractall(root)
VT_BUNDLE_PYTHON
export PYTHONPATH="$vt_tmp/src"
export PYTHONDONTWRITEBYTECODE=1
python3 -m vt.install "$@"
'''
    return shell.replace("__PAYLOAD__", lines).replace("__HASH__", hashlib.sha256(payload).hexdigest()).encode()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = build()
    path = ROOT / "install.sh"
    if args.check:
        if not path.exists() or path.read_bytes() != result:
            raise SystemExit("install.sh is out of date. Run python3 tools/build_installer.py")
        print("install.sh matches the source tree.")
    else:
        path.write_bytes(result)
        print("Created install.sh (%d bytes)" % len(result))


if __name__ == "__main__":
    main()
